name: VoteParty
main: me.clip.voteparty.plugin.VotePartyPlugin

version: '@version@'
authors: ['Clip']

depend:
  - 'PlaceholderAPI'
softdepend:
  - 'Votifier'

api-version: '1.13'
description: 'Heavily modified VoteParty version by xism4'


permissions:
  voteparty.command.admin:
    description: 'Ability to use all admin commands'
    default: op
  voteparty.command.claim:
    description: 'Ability to claim offline vote rewards'
    default: true